text = input('Digite algo: ')

print('O tipo primitivo desse valor é {}'.format(type(text)))
print('Só tem espaços? {}'.format(text.isspace()))
print('É um número? {}'.format(text.isnumeric()))
print('É alfabético? {}'.format(text.isalpha()))
print('É alfanumérico? {}'.format(text.isalnum()))
print('Está em maiusculas? {}'.format(text.isupper()))
print('Está em minusculas? {}'.format(text.islower()))
print('Está capitalizada? {}'.format(text.istitle()))